### ISSUE TITLE
Make program downward-compatible with older Python versions

### ISSUE THREAD

**Issue by thunfischtoast** [Informationsfabrik/ml_tetris_hacksession#2]
Currently the only thing that makes Python 3.10 obligate are the type hints - on the Hack not all people had Python 3.10 installed. In principle it should not be a problem to make it work with Python 3.8 or less

**Comment by CommentatorForAll** [comment]
Type hints were introduced in 3.5 under [Pep 484](https://peps.python.org/pep-0484/) The reason we require 3.10 currently is the usage of the pipe delimeter for multiple types (e.g. [here](https://github.com/Informationsfabrik/ml_tetris_hacksession/blob/8dee270100e6edac1203081af22b6d8c1d192147/src/teachable_machine_testing.py#L14)) which was only introduced in 3.10 via [pep 604](https://peps.python.org/pep-0604/) to fix it, one can use the `Union[]` type from the typing package.
